# Generated by Django 4.2.1 on 2023-05-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_badword'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
